### Linear Algebra

In [1]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([7,9,6])

In [2]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
vector

array([7, 9, 6])

In [4]:
matrix.shape

(2, 3)

In [5]:
vector.shape

(3,)

#### Matrix and Scalar Operation

#### Addition

In [6]:
matrix + 3

array([[4, 5, 6],
       [7, 8, 9]])

#### Subtraction

In [10]:
matrix - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

#### Multiplication


In [11]:
matrix * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

#### Division

In [12]:
matrix / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

### Matrix and Matrix General Addition and Subtraction

#### Adition

In [19]:
matrix1 = np.array([
                   [1,2],
                   [3,4]
                  ])
matrix2 = np.array([
                   [1,2],
                   [3,4] 
                  ])
print("New Matrix = \n", matrix1 + matrix2)

New Matrix = 
 [[2 4]
 [6 8]]


#### Multiplication

In [24]:
matrix1 = np.array([
    [2,3],
    [2,3]
])

matrix2 = np.array([
    [3,4],
    [5,6]
])

print("New matrix = \n", matrix1 * matrix2)

New matrix = 
 [[ 6 12]
 [10 18]]


#### Matrix and Matrix Dot Multiplication

In [25]:
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

matrix1.dot(matrix2)

array([[ 58,  64],
       [139, 154]])

#### Transpose Matrix

In [28]:
matrix1 = np.array([
    [1, 2, 0],
    [3, 5, 9]
])

matrix1.T

array([[1, 3],
       [2, 5],
       [0, 9]])

#### Identity Matrix

In [27]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Inverse Matrix

In [29]:
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, -6],
    [7, -8, 9]
])

print(np.linalg.inv(matrix1))

[[ 0.00833333  0.11666667  0.075     ]
 [ 0.21666667  0.03333333 -0.05      ]
 [ 0.18611111 -0.06111111  0.00833333]]
