#### Read the dataset

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('GPA.csv')
df

Name  StudyTime  GamingHour   GPA
0   Monir        4.0         0.5  3.55
1    Jony        2.5         1.0  2.35
2   Gopal        3.0         0.5  3.07
3   Habib        6.0         0.0  3.93
4    Kona        5.0         0.5  3.97
5   Bablu        1.0         3.0  2.43
6    Sara        3.5         0.0  3.61
7   Javed        4.0         0.5  3.67
8   Hasib        2.0         1.0  2.97
9  Hridoy        1.5         2.0  2.81

#### Use of count function

In [2]:
df.count()

Name          10
StudyTime     10
GamingHour    10
GPA           10
dtype: int64

#### Adding all the values of a variable

In [4]:
df['GamingHour'].sum()

9.0

#### Use of cumulative sam

In [6]:
df['GamingHour'].cumsum()

0    0.5
1    1.5
2    2.0
3    2.0
4    2.5
5    5.5
6    5.5
7    6.0
8    7.0
9    9.0
Name: GamingHour, dtype: float64

#### Use of mean function

In [7]:
df.mean()

StudyTime     3.250
GamingHour    0.900
GPA           3.236
dtype: float64

#### Use of median

In [9]:
df.median()

StudyTime     3.25
GamingHour    0.50
GPA           3.31
dtype: float64

#### Determine the mode of a variable

In [11]:
df['StudyTime'].mode()

0    4.0
dtype: float64

#### Maximum and minimum diagnosis

In [12]:
df.max()

Name          Sara
StudyTime      6.0
GamingHour     3.0
GPA           3.97
dtype: object

In [13]:
df.min()

Name          Bablu
StudyTime       1.0
GamingHour      0.0
GPA            2.35
dtype: object

#### Diagnosis the range

In [22]:
#range = df[['StudyTime','GamingHour','GPA']].max()- df[['StudyTime','GamingHour','GPA']].min()
range = df.loc[:, df.columns != 'Name'].max()-df.loc[:, df.columns !='Name'].min()
range

StudyTime     5.00
GamingHour    3.00
GPA           1.62
dtype: float64

#### Determine the Variance

In [23]:
df.var()

StudyTime     2.458333
GamingHour    0.877778
GPA           0.351293
dtype: float64

#### Determine the Standard Deviation

In [24]:
df.std()

StudyTime     1.567907
GamingHour    0.936898
GPA           0.592700
dtype: float64

#### Determine the Covariance Matrix

In [25]:
df.cov()

StudyTime  GamingHour       GPA
StudyTime    2.458333   -1.194444  0.827222
GamingHour  -1.194444    0.877778 -0.418222
GPA          0.827222   -0.418222  0.351293

### Determine the corelation matrix

In [26]:
df.corr()

StudyTime  GamingHour       GPA
StudyTime    1.000000   -0.813117  0.890157
GamingHour  -0.813117    1.000000 -0.753147
GPA          0.890157   -0.753147  1.000000

#### Determine the Skewness and Kurtosis

In [27]:
df.skew()

StudyTime     0.283764
GamingHour    1.499697
GPA          -0.283563
dtype: float64

In [28]:
df.kurtosis()

StudyTime    -0.548118
GamingHour    1.985173
GPA          -1.396490
dtype: float64

#### Diagnosis of Quantiles and Inter Quantile Range

In [30]:
df.quantile(.25)

StudyTime     2.125
GamingHour    0.500
GPA           2.850
Name: 0.25, dtype: float64

In [31]:
iqr = df.quantile(.75)-df.quantile(.25)
iqr

StudyTime     1.875
GamingHour    0.500
GPA           0.805
dtype: float64

#### Use of Describe Function

In [1]:
df.describe()

NameError: name 'df' is not defined

In [17]:
num = [1, 2, 3, 4, 5]

In [18]:
result = list(filter(lambda x : x%2==0, num))
result

[2, 4]

In [21]:
result = [x for x in num if x%2==0]
result

[2, 4]

In [22]:
squares = []
for number in num:
    sq = number ** 2
    squares.append(sq)
squares
    

[1, 4, 9, 16, 25]

In [24]:
[x**2 for x in num]

[1, 4, 9, 16, 25]

In [26]:
import pandas as pd
data = pd.DataFrame()
data['population'] = [47, 48, 85, 20, 19, 13, 72, 16, 50, 60]
data

population
0          47
1          48
2          85
3          20
4          19
5          13
6          72
7          16
8          50
9          60

In [29]:
a_sample_without_replacement = data['population'].sample(5, replace=False)
a_sample_with_replacement = data['population'].sample(5, replace=True)

In [31]:
a_sample_without_replacement


1    48
2    85
0    47
3    20
4    19
Name: population, dtype: int64

In [32]:
a_sample_with_replacement

7    16
7    16
0    47
0    47
4    19
Name: population, dtype: int64

In [41]:
print('Population mean is', data['population'].mean())
print('Population variance is', data['population'].var(ddof=0))
print('Population standard deviation is', data['population'].std(ddof=0))
print('Population size is', data['population'].shape[0])

Population mean is 43.0
Population variance is 635.3333333333334
Population standard deviation is 25.20581943387942
Population size is 10


In [43]:
print('Sample mean is', a_sample_with_replacement.mean())
print('Sample variane is', a_sample_with_replacement.var(ddof=1))
print('Sample std is', a_sample_with_replacement.std(ddof=1))
print('Sample size is', a_sample_with_replacement.shape[0])

Sample mean is 29.0
Sample variane is 271.5
Sample std is 16.47725705328408
Sample size is 5


In [45]:
print('Sample mean is', a_sample_without_replacement.mean())
print('Sample variane is', a_sample_without_replacement.var(ddof=1))
print('Sample std is', a_sample_without_replacement.std(ddof=1))
print('Sample size is', a_sample_without_replacement.shape[0])

Sample mean is 43.8
Sample variane is 726.7
Sample std is 26.95737375932604
Sample size is 5


In [51]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([7,8,9])

In [49]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
vector

array([7, 8, 9])

In [53]:
matrix.shape

(2, 3)

In [54]:
vector.shape

(3,)

In [55]:
matrix+3

array([[4, 5, 6],
       [7, 8, 9]])

In [56]:
matrix-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [57]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a+b

array([[2, 4],
       [6, 8]])

In [58]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8],[9,10],[11,12]])
m1.dot(m2)

array([[ 58,  64],
       [139, 154]])

In [59]:
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np

In [3]:
vector = np.array([7,8,9])
vector

array([7, 8, 9])

In [139]:
subject_name = np.array(["Jone Doe", "Jane Doe", "Steve Graves"])
temperature = np.array([98.1, 98.6, 101.4])
#flu_status = np.array([False, False, True])

In [99]:
temperature[1]

98.6

In [65]:
temperature[1:3]

array([ 98.6, 101.4])

In [66]:
temperature[-2:-1]

array([98.6])

In [74]:
temperature = list(temperature)

In [70]:
#temperature.pop(1)

98.6

In [75]:
temperature

[98.1, 98.6, 101.4]

In [78]:
gender = np.array(["Male", "Female", "Male"])
gender

array(['Male', 'Female', 'Male'], dtype='<U6')

In [79]:
blood = np.array(["O","AB","A"])
blood

array(['O', 'AB', 'A'], dtype='<U2')

In [87]:
subject1 = {
    "fullname" : subject_name[0],
    "temperature" : temperature[0],
    "flu_status" : flu_status[0],
    "gender" : gender[0],
    "blood" : blood[0]
}

In [88]:
subject1

{'fullname': 'Jone Doe',
 'temperature': 98.1,
 'flu_status': False,
 'gender': 'Male',
 'blood': 'O'}

In [108]:
subject1['temperature']

98.1

In [133]:
keys = ['temperature', 'flu_status', 'gender']

for key in keys:
    print(subject1[key])

98.1
False
Male


In [100]:
subject2 = [subject_name[0],temperature[0],flu_status[0],gender[0],blood[0]]
subject2

['Jone Doe', 98.1, False, 'Male', 'O']

In [105]:
subject2[1:3]

[98.1, False]

In [106]:
subject3 = [temperature[0],flu_status[0]]
subject3

[98.1, False]

In [ ]:
df = pd.DataFrame(data={'a' : np.array([1,2,3], dtype=int),
                        'b' : np.array([4,5,6], dtype=float)
                       }
                 )

convert_dict = {'a': int, 'b': float}
df = df.astype(convert_dict)

In [152]:
import pandas as pd

df = pd.DataFrame({'Patient_name': subject_name, 'Temperature': temperature, 'Flu_status': flu_status,'Gender':gender, 'Blood':blood})
df

Patient_name  Temperature  Flu_status  Gender Blood
0      Jone Doe         98.1       False    Male     O
1      Jane Doe         98.6       False  Female    AB
2  Steve Graves        101.4        True    Male     A

In [168]:
df[['Patient_name', 'Flu_status']]

Patient_name  Flu_status
0      Jone Doe       False
1      Jane Doe       False
2  Steve Graves        True

In [164]:
df['Temperature'][0]

98.1

In [174]:
df[0:2]

Patient_name  Temperature  Flu_status  Gender Blood
0     Jone Doe         98.1       False    Male     O
1     Jane Doe         98.6       False  Female    AB